// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBekmZBn-JaAlb9YjdI1bR_MTbbD09lVj8',
    appId: '1:41909711604:web:8e0862b98f5e0e12ada4a1',
    messagingSenderId: '41909711604',
    projectId: 'studentlife-1b6d7',
    authDomain: 'studentlife-1b6d7.firebaseapp.com',
    storageBucket: 'studentlife-1b6d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnsQKS36WS9oLQoGqUgfxVg1bZKD24GpE',
    appId: '1:41909711604:android:83d52a8df0ac8df7ada4a1',
    messagingSenderId: '41909711604',
    projectId: 'studentlife-1b6d7',
    storageBucket: 'studentlife-1b6d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjqIQsXdwsXCYio_gxYzscf81N-2xJN1Q',
    appId: '1:41909711604:ios:ea2ecd19f5081ebaada4a1',
    messagingSenderId: '41909711604',
    projectId: 'studentlife-1b6d7',
    storageBucket: 'studentlife-1b6d7.firebasestorage.app',
    iosBundleId: 'com.example.eduria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjqIQsXdwsXCYio_gxYzscf81N-2xJN1Q',
    appId: '1:41909711604:ios:ea2ecd19f5081ebaada4a1',
    messagingSenderId: '41909711604',
    projectId: 'studentlife-1b6d7',
    storageBucket: 'studentlife-1b6d7.firebasestorage.app',
    iosBundleId: 'com.example.eduria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBekmZBn-JaAlb9YjdI1bR_MTbbD09lVj8',
    appId: '1:41909711604:web:6334a7380c670269ada4a1',
    messagingSenderId: '41909711604',
    projectId: 'studentlife-1b6d7',
    authDomain: 'studentlife-1b6d7.firebaseapp.com',
    storageBucket: 'studentlife-1b6d7.firebasestorage.app',
  );
}
